enforce_ssl: al3x.net
highlighter: rouge
livereload: true
lsi: false
markdown: kramdown
port: 3000
url: https://al3x.net
twitter_username:     r3bl_
github_username:      aleksandar-todorovic
linkedin_username:    aleksandartodorovic
google_plus_username: AleksandarTodorovićr3bl
facebook_username:    aleksandar.todorovic.r3bl
dribbble_username:
